### ISSUE TITLE
Unregistered user still in the database, marked inactive

### ISSUE THREAD

**Issue by fft-ucd** [thiagohora/COMP47910-project#6]
should an unregistered user be removed from the database, it looks like it is marked inactive but still present (see screenshot)

![image](https://github.com/thiagohora/COMP47910-project/assets/139648396/20075774-f917-4d0f-8870-01e0b7302f75)

**Comment by thiagohora** [comment]
Yes, it is a soft delete. Is it required to be deleted?

**Comment by fft-ucd** [comment]
I think you are right, it was not a requirement that the user is permanently deleted from the database, only from the system. I am sure even at work I would have arguments about whether we should remove them permanently or not. I would argue in favour of removing them but in this case I think it is fine.
