### ISSUE TITLE
Users not registered as Active: Null entry in the Inactive field in the User table instead of a Zero

### ISSUE THREAD

**Issue by fft-ucd** [thiagohora/COMP47910-project#7]
BUG or ENVIRONMENTAL ISSUE?

I registered one user in Starwood successfully. I then inactivated it. Ever since when I register new users the value in the inactive column of the user table in the database is NULL. The registration is successful but I cannot log in (I had tested that I was able to log in as a registered user and retrieve my reservations). The very strange thing is that I have restarted backend, frontend, mysql and browser and I'm still getting the same problem. Could you please let me know if you can replicate this behaviour?

The NULL value is the problem because when I try to log in with a newly created user (after receiving the User Successfully registered message) is 
`java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "com.marriott.webapp.model.User.getInactive()" is null`

I verified that modifying the value of user.inactive (replacing NULL with 0) fixes the problem for that user.

Even using Incognito windows, even after rebooting the laptop, I get the same problem. I wiped the entire project and created a brand new one, still same problem. Could you please let me know if this happens to you too? I struggle to understand what might be causing it.

**Comment by thiagohora** [comment]
Done

**Comment by fft-ucd** [comment]
Hi Thiago, nice job. It works for me now, I tested a few scenarios including disabling user, creating new ones, using email as usernames. All's good. I looked at the changes in the code but, apart for the Protected Boolean, I'm not sure I understand. Perhaps we can catch up tomorrow. Thanks again!
